---
- hosts: localhost
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: Testing1
      location: eastus
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: Testing1
      name: testvm10
      admin_username: sysadmin
      admin_password: test@123456789
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest